package com.kpis.helper.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StaffAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffAllPropertiesEquals(Staff expected, Staff actual) {
        assertStaffAutoGeneratedPropertiesEquals(expected, actual);
        assertStaffAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffAllUpdatablePropertiesEquals(Staff expected, Staff actual) {
        assertStaffUpdatableFieldsEquals(expected, actual);
        assertStaffUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffAutoGeneratedPropertiesEquals(Staff expected, Staff actual) {
        assertThat(expected)
            .as("Verify Staff auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffUpdatableFieldsEquals(Staff expected, Staff actual) {
        assertThat(expected)
            .as("Verify Staff relevant properties")
            .satisfies(e -> assertThat(e.getRecorded_date()).as("check recorded_date").isEqualTo(actual.getRecorded_date()))
            .satisfies(e -> assertThat(e.getNumber_of_staff()).as("check number_of_staff").isEqualTo(actual.getNumber_of_staff()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaffUpdatableRelationshipsEquals(Staff expected, Staff actual) {}
}
